name: Test Swiq

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Swiq
        run: "mkdir build && cd build && cmake .. && make"

      - name: Run test 1
        run: "cp ./swiq ../ && cd ../ && ./swiq examples/hello.swiq"
